# Generated by Django 4.2.2 on 2023-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
