# Generated by Django 4.2.2 on 2023-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorAndNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_code', models.CharField(blank=True, default='', max_length=10, null=True, unique=True)),
                ('notify_short_description', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
