# Generated by Django 4.2.2 on 2023-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_errorandnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=2, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accepteddomain',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='accepteddomain',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='errorandnotification',
            name='notify_code',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='errorandnotification',
            name='notify_short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
