# Generated by Django 4.2.2 on 2023-06-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_delete_accounttype_alter_accepteddomain_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepteddomain',
            options={'verbose_name_plural': 'Accepted domains'},
        ),
        migrations.AlterModelOptions(
            name='errorandnotification',
            options={'verbose_name_plural': 'Errors and notifications'},
        ),
    ]
