# Generated by Django 4.2.2 on 2023-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('fiscal_code', models.CharField(blank=True, default='', max_length=12, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, default='', max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email_address', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=10, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('sales_price_with_vat', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('barcode', models.CharField(blank=True, default='', max_length=13)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('fiscal_code', models.CharField(blank=True, default='', max_length=12, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, default='', max_length=20, null=True, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email_address', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
