# Generated by Django 4.2.2 on 2023-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
    ]
