# Generated by Django 4.2.2 on 2023-07-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_city_county_company_economic_activity_and_more'),
        ('files', '0005_alter_client_is_active_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='configurations.accounttype'),
        ),
    ]
