# Generated by Django 4.2.2 on 2023-07-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_companydetails_city_companydetails_country_and_more'),
        ('files', '0006_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_city', to='configurations.city'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_country', to='configurations.country'),
        ),
        migrations.AddField(
            model_name='client',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_county', to='configurations.county'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_product_type', to='configurations.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_unit_of_measurement', to='configurations.unitofmeasurement'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_vat_type', to='configurations.vattype'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_city', to='configurations.city'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_country', to='configurations.country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_county', to='configurations.county'),
        ),
    ]
