# Generated by Django 4.2.2 on 2023-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=2, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
