# Generated by Django 4.2.2 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_alter_accounttype_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name_plural': 'Account types'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='currencycode',
            options={'verbose_name_plural': 'Currency codes'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name_plural': 'Document types'},
        ),
        migrations.AlterModelOptions(
            name='economicactivity',
            options={'verbose_name_plural': 'Economic activities'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasurement',
            options={'verbose_name_plural': 'Unit of measurements'},
        ),
        migrations.AlterModelOptions(
            name='vattype',
            options={'verbose_name_plural': 'Vat types'},
        ),
        migrations.AlterModelOptions(
            name='warehousetype',
            options={'verbose_name_plural': 'Warehouse types'},
        ),
        migrations.AlterField(
            model_name='warehousetype',
            name='type',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
