# Generated by Django 4.2.2 on 2023-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_accounttype_added_by_city_added_by_company_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='currencycode',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='economicactivity',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='vattype',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='warehousetype',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
    ]
