# Generated by Django 4.2.2 on 2023-07-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_companysettings_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='configurations.county'),
        ),
        migrations.AddField(
            model_name='company',
            name='economic_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='configurations.economicactivity'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details', to='configurations.company'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='configurations.company'),
        ),
        migrations.AddField(
            model_name='county',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='configurations.country'),
        ),
        migrations.AddField(
            model_name='currencycode',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_codes', to='configurations.country'),
        ),
    ]
