# Generated by Django 4.2.2 on 2023-07-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_city_county_company_economic_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_city', to='configurations.city'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_country', to='configurations.country'),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_county', to='configurations.county'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_details_company', to='configurations.company'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings_company', to='configurations.company'),
        ),
    ]
