# Generated by Django 4.2.2 on 2023-07-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_companydetails_city_companydetails_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_county', to='configurations.county'),
        ),
        migrations.AlterField(
            model_name='company',
            name='economic_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies_economic_activity', to='configurations.economicactivity'),
        ),
        migrations.AlterField(
            model_name='county',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counties_country', to='configurations.country'),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_codes_country', to='configurations.country'),
        ),
    ]
