# Generated by Django 4.2.2 on 2023-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAndBankRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=23, unique=True)),
                ('document_note', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('sum_received', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('sum_payed', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('is_cash_register', models.BooleanField(blank=True, default=False, null=True)),
                ('is_bank_register', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cash and Bank Register',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=23, unique=True)),
                ('document_note', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Consumption receipts',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(blank=True)),
                ('unit_gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('vat_amount_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('unit_net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Consumption receipt lines',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default='', max_length=23, unique=True)),
                ('vat_on_cash_received', models.BooleanField(blank=True, default=False, null=True)),
                ('document_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('document_due_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(blank=True)),
                ('unit_gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('vat_amount_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('unit_net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Invoice lines',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default='', max_length=23, unique=True)),
                ('electronic_invoice', models.BooleanField(blank=True, default=False, null=True)),
                ('document_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('document_due_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Sales invoices',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(blank=True)),
                ('unit_gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('vat_amount_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('unit_net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Sales invoice lines',
            },
        ),
        migrations.CreateModel(
            name='ShippingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, default='', max_length=23, unique=True)),
                ('document_date', models.DateTimeField(blank=True, default='', max_length=36, unique=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('document_note', models.CharField(blank=True, default='', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping notes',
            },
        ),
        migrations.CreateModel(
            name='ShippingNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(blank=True)),
                ('unit_gross_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('vat_amount_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
                ('unit_net_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name_plural': 'Shipping note lines',
            },
        ),
    ]
