# Generated by Django 4.2.2 on 2023-07-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashandbankregister',
            options={'verbose_name_plural': 'Cash and bank register'},
        ),
    ]
