# Generated by Django 4.2.2 on 2023-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_cashandbankregister_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashandbankregister',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='consumptionreceipt',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='consumptionreceiptline',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippingnote',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippingnoteline',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cashandbankregister',
            name='is_bank_register',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cashandbankregister',
            name='is_cash_register',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_on_cash_received',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='electronic_invoice',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
    ]
