# Generated by Django 4.2.2 on 2023-07-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_client_account_supplier_account_and_more'),
        ('configurations', '0011_alter_city_county_alter_company_economic_activity_and_more'),
        ('operations', '0005_consumptionreceipt_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionreceipt',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_receipts_invoice', to='operations.invoice'),
        ),
        migrations.AddField(
            model_name='consumptionreceiptline',
            name='consumption_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_receipt_lines_consumption_receipt', to='operations.consumptionreceipt'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_supplier', to='files.supplier'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines_account', to='files.account'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines_invoice', to='operations.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines_product', to='files.product'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices_client', to='files.client'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_lines_account', to='files.account'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_lines_product', to='files.product'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_lines_sales_invoice', to='operations.salesinvoice'),
        ),
        migrations.AddField(
            model_name='shippingnote',
            name='sales_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_notes_sales_invoice', to='operations.salesinvoice'),
        ),
        migrations.AddField(
            model_name='shippingnoteline',
            name='shipping_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_note_lines_sales_invoice', to='operations.shippingnote'),
        ),
        migrations.AlterField(
            model_name='consumptionreceipt',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_receipts_document_type', to='configurations.documenttype'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices_document_type', to='configurations.documenttype'),
        ),
        migrations.AlterField(
            model_name='shippingnote',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_notes_document_type', to='configurations.documenttype'),
        ),
    ]
